local constants = T{
    moonPhasePercent = T{
        [1] = 100,
        [2] = 98,
        [3] = 95,
        [4] = 93,
        [5] = 90,
        [6] = 88,
        [7] = 86,
        [8] = 83,
        [9] = 81,
        [10] = 79,
        [11] = 76,
        [12] = 74,
        [13] = 71,
        [14] = 69,
        [15] = 67,
        [16] = 64,
        [17] = 62,
        [18] = 60,
        [19] = 57,
        [20] = 55,
        [21] = 52,
        [22] = 50,
        [23] = 48,
        [24] = 45,
        [25] = 43,
        [26] = 40,
        [27] = 38,
        [28] = 36,
        [29] = 33,
        [30] = 31,
        [31] = 29,
        [32] = 26,
        [33] = 24,
        [34] = 21,
        [35] = 19,
        [36] = 17,
        [37] = 14,
        [38] = 12,
        [39] = 10,
        [40] = 7,
        [41] = 5,
        [42] = 2,
        [43] = 0,
        [44] = 2,
        [45] = 5,
        [46] = 7,
        [47] = 10,
        [48] = 12,
        [49] = 14,
        [50] = 17,
        [51] = 19,
        [52] = 21,
        [53] = 24,
        [54] = 26,
        [55] = 29,
        [56] = 31,
        [57] = 33,
        [58] = 36,
        [59] = 38,
        [60] = 40,
        [61] = 43,
        [62] = 45,
        [63] = 48,
        [64] = 50,
        [65] = 52,
        [66] = 55,
        [67] = 57,
        [68] = 60,
        [69] = 62,
        [70] = 64,
        [71] = 67,
        [72] = 69,
        [73] = 71,
        [74] = 74,
        [75] = 76,
        [76] = 79,
        [77] = 81,
        [78] = 83,
        [79] = 86,
        [80] = 88,
        [81] = 90,
        [82] = 93,
        [83] = 95,
        [84] = 98
    };

    moonPhase = T{
        [1] = 'Full Moon',
        [2] = 'Full Moon',
        [3] = 'Full Moon',
        [4] = 'Waning Gibbous',
        [5] = 'Waning Gibbous',
        [6] = 'Waning Gibbous',
        [7] = 'Waning Gibbous',
        [8] = 'Waning Gibbous',
        [9] = 'Waning Gibbous',
        [10] = 'Waning Gibbous',
        [11] = 'Waning Gibbous',
        [12] = 'Waning Gibbous',
        [13] = 'Waning Gibbous',
        [14] = 'Waning Gibbous',
        [15] = 'Waning Gibbous',
        [16] = 'Waning Gibbous',
        [17] = 'Waning Gibbous',
        [18] = 'Last Quarter',
        [19] = 'Last Quarter',
        [20] = 'Last Quarter',
        [21] = 'Last Quarter',
        [22] = 'Last Quarter',
        [23] = 'Last Quarter',
        [24] = 'Last Quarter',
        [25] = 'Last Quarter',
        [26] = 'Waning Crescent',
        [27] = 'Waning Crescent',
        [28] = 'Waning Crescent',
        [29] = 'Waning Crescent',
        [30] = 'Waning Crescent',
        [31] = 'Waning Crescent',
        [32] = 'Waning Crescent',
        [33] = 'Waning Crescent',
        [34] = 'Waning Crescent',
        [35] = 'Waning Crescent',
        [36] = 'Waning Crescent',
        [37] = 'Waning Crescent',
        [38] = 'Waning Crescent',
        [39] = 'New Moon',
        [40] = 'New Moon',
        [41] = 'New Moon',
        [42] = 'New Moon',
        [43] = 'New Moon',
        [44] = 'New Moon',
        [45] = 'New Moon',
        [46] = 'Waxing Crescent',
        [47] = 'Waxing Crescent',
        [48] = 'Waxing Crescent',
        [49] = 'Waxing Crescent',
        [50] = 'Waxing Crescent',
        [51] = 'Waxing Crescent',
        [52] = 'Waxing Crescent',
        [53] = 'Waxing Crescent',
        [54] = 'Waxing Crescent',
        [55] = 'Waxing Crescent',
        [56] = 'Waxing Crescent',
        [57] = 'Waxing Crescent',
        [58] = 'Waxing Crescent',
        [59] = 'First Quarter',
        [60] = 'First Quarter',
        [61] = 'First Quarter',
        [62] = 'First Quarter',
        [63] = 'First Quarter',
        [64] = 'First Quarter',
        [65] = 'First Quarter',
        [66] = 'First Quarter',
        [67] = 'Waxing Gibbous',
        [68] = 'Waxing Gibbous',
        [69] = 'Waxing Gibbous',
        [70] = 'Waxing Gibbous',
        [71] = 'Waxing Gibbous',
        [72] = 'Waxing Gibbous',
        [73] = 'Waxing Gibbous',
        [74] = 'Waxing Gibbous',
        [75] = 'Waxing Gibbous',
        [76] = 'Waxing Gibbous',
        [77] = 'Waxing Gibbous',
        [78] = 'Waxing Gibbous',
        [79] = 'Waxing Gibbous',
        [80] = 'Waxing Gibbous',
        [81] = 'Full Moon',
        [82] = 'Full Moon',
        [83] = 'Full Moon',
        [84] = 'Full Moon'
    };

    clammingItems = {
        { item="Bibiki slug",				weight=3,	gil=T{10}, 	vendor = true},
        { item="Bibiki urchin", 			weight=6,	gil=T{750}, 	vendor = true},
        { item="Broken willow fishing rod",	weight=6,	gil=T{0}, 		vendor = false},
        { item="Coral fragment",			weight=6,	gil=T{1750}, 	vendor = true},
        { item="Quality crab shell",	    weight=6,	gil=T{3312}, 	vendor = true}, --Note: For some reason using "High-quality" doesn't register properly, leave as "Quality" for the time being
        { item="Crab shell",				weight=6,	gil=T{371}, 	vendor = true},  --Make sure HQ version is listed above NQ for proper registering of item
        { item="Elshimo coconut", 			weight=6,	gil=T{44}, 	vendor = true},
        { item="Elm log", 					weight=6,	gil=T{4000}, 	vendor = false}, --Based on estimated AH value
        { item="Fish scales",				weight=3,	gil=T{24}, 	vendor = true},
        { item="Goblin armor",				weight=6,	gil=T{0}, 		vendor = false},   --Based on estimated AH value
        { item="Goblin mail", 				weight=6,	gil=T{1000}, 	vendor = false}, --Based on estimated AH value
        { item="Goblin mask", 				weight=6,	gil=T{0}, 		vendor = false},  --Based on estimated AH value
        { item="Hobgoblin bread", 			weight=6,	gil=T{91}, 	vendor = true},
        { item="Hobgoblin pie", 			weight=6,	gil=T{150}, 	vendor = true},
        { item="Igneous rock", 				weight=35,	gil=T{178}, 	vendor = true},
        { item="Jacknife", 					weight=11,	gil=T{53}, 	vendor = true},
        { item="Lacquer tree log", 			weight=6,	gil=T{6000}, 	vendor = false}, --Based on estimated AH value
        { item="Maple log", 				weight=6,	gil=T{15}, 	vendor = true},
        { item="Nebimonite", 				weight=6,	gil=T{53}, 	vendor = true},
        { item="Oxblood", 					weight=6,	gil=T{13250}, 	vendor = true},
        { item="Pamamas", 					weight=6,	gil=T{20}, 	vendor = true},
        { item="Pamtam kelp", 				weight=6,	gil=T{8}, 		vendor = true},
        { item="Pebble", 					weight=7,	gil=T{1}, 		vendor = true},
        { item="Petrified log", 			weight=6,	gil=T{2193}, 	vendor = true}, 
        { item="Quality pugil scales",		weight=6,	gil=T{260}, 	vendor = true},  --Note: For some reason using "High-quality" doesn't register properly, leave as "Quality" for the time being
        { item="Pugil scales", 				weight=3,	gil=T{23}, 	vendor = true},   --Make sure HQ version is listed above NQ for proper registering of item
        { item="Rock salt",					weight=6,	gil=T{3}, 		vendor = true},
        { item="Seashell", 					weight=6,	gil=T{30}, 	vendor = true},
        { item="Shall shell",				weight=6,	gil=T{300}, 	vendor = true},
        { item="Titanictus shell", 			weight=6,	gil=T{350}, 	vendor = true},
        { item="Tropical clam", 			weight=20,	gil=T{5100}, 	vendor = true},
        { item="Turtle shell", 				weight=6,	gil=T{1224}, 	vendor = true},
        { item="Uragnite shell", 			weight=6,	gil=T{1455}, 	vendor = true},
        { item="Vongola clam", 				weight=6,	gil=T{192}, 	vendor = true},
        { item="White sand",				weight=7,	gil=T{250}, 	vendor = true},
    };
}

return constants;